branch-defaults:
  default:
    environment: grind-app-dev
  master:
    environment: grind-app-dev
global:
  application_name: grind_app
  default_ec2_keyname: aws-eb3
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
